version: 0.2
env:
  parameter-store:
    GithubToken: githubtoken
phases:
  install:
    on-failure: ABORT
    runtime-versions:
      nodejs: 20
    commands:
      # Install all dependencies (including dependencies for running tests)
      - npm config set @idexcel-technologies-pvt-ltd:registry https://npm.pkg.github.com/
      - npm config set //npm.pkg.github.com/:_authToken=$GithubToken
      - npm install
  pre_build:
    on-failure: ABORT
    commands:
      - npm test
      # Comment out database certificate download since we're not connecting to database for now
      # - mkdir -p certificates
      # - aws s3 cp s3://$PUB_CERT_BUCKET_NAME/ certificates/  --recursive 1>> stdout
      - eval $PreBuildScript
  build:
    on-failure: ABORT
    commands:
    - npm run build-prod
  post_build:
    on-failure: ABORT
    commands:
    # Use AWS SAM to package the application by using AWS CloudFormation
      - mkdir -p artifacts
      - aws cloudformation package --template-file template.yml --s3-bucket $BUILD_OUTPUT_BUCKET --s3-prefix $BUILD_OUTPUT_PREFIX --output-template-file artifacts/packaged.yaml
      - eval $PostBuildScript
artifacts:
  type: zip
  files:
  - 'artifacts/**/*'
  secondary-artifacts:
    Build:
      files:
        -  'artifacts/**/*'
    UploadArtifacts:
      name: UploadArtifacts
      discard-paths: yes
      files:
        - 'src/**/*'
        - 'build/**/*'
